package web

import (
	"fmt"
	"strings"

	"github.com/seolcu/hostveil/internal/model"
)

// domainsJS renders the detection-domain table the page needs to turn a
// finding's numeric source into something a human reads.
//
// It is generated for the same reason /themes.css and /theme.js are. The
// dashboard used to carry its own copy as a JavaScript object literal, and
// nothing tied it to model.Source; when the sysctl domain was added the
// copy was not, and the dashboard silently stopped offering a filter chip
// for a whole domain while rendering its failures as a bare "10". A table
// the engine emits cannot fall behind the engine.
//
// Only the domain table is generated. The severity, remediation, and scan
// state enums are mirrored in app.js too, and deliberately left there:
// those are closed sets that have not changed and have no documented way
// to grow, while "add a detection domain" is a routine extension with its
// own checklist in internal/model/source.go. Generating what cannot drift
// would be ceremony; generating what already did is the fix.
func domainsJS() string {
	var b strings.Builder
	b.WriteString("/* Generated by internal/ui/web from model.AllSources — do not edit by hand. */\n")
	b.WriteString("window.HOSTVEIL_DOMAINS = {\n")
	for _, s := range model.AllSources() {
		fmt.Fprintf(&b, "  %d: {id: %q, label: %q},\n", int(s), s.String(), s.Label())
	}
	b.WriteString("};\n")
	return b.String()
}
