package web

import (
	"regexp"
	"strings"
	"testing"
)

// Every band in the dashboard starts hidden and is shown when the host has
// something to put in it: the since-last-scan summary, the score trend, the
// coverage notice, the transient status line, the batch bar.
//
// `el.hidden = true` is how app.js puts one away, and on its own that does
// not work here. The UA stylesheet declares [hidden] at the specificity of a
// single class, so `.delta { display: flex }` — later in app.css, same
// specificity — simply wins, and the element stays laid out. What that
// produced was not a broken page but a quieter thing: a band of empty
// padding with a border under it, once for every band the host had nothing
// to say in, in every arrangement. On a first scan that was three rules of
// nothing stacked under the axes strip.
//
// So each of them needs its own [hidden] rule, or a base rule that is
// display:none until something turns it on. This walks the elements that
// carry the attribute in index.html rather than a list typed out here, so a
// band added later is covered the moment it is written.
//
// Not solved with a blanket `[hidden] { display: none !important }`:
// .verdict and .rail deliberately stay hidden in the DOM and are un-hidden
// per arrangement by the layout rules at the end of app.css, and an
// !important would beat those and delete the rail from the two layouts built
// around it.
func TestEveryBandThatStartsHiddenStaysHidden(t *testing.T) {
	html, err := assets.ReadFile("assets/index.html")
	if err != nil {
		t.Fatal(err)
	}
	css, err := assets.ReadFile("assets/app.css")
	if err != nil {
		t.Fatal(err)
	}
	sheet := string(css)

	// class="…" … hidden, on one tag. The attribute order is fixed by the
	// file, which is generated by nothing and edited by hand.
	tag := regexp.MustCompile(`<[a-z]+ class="([a-z0-9 -]+)"[^>]*\shidden\s*>`)
	found := tag.FindAllStringSubmatch(string(html), -1)
	if len(found) == 0 {
		t.Fatal("no elements with a hidden attribute in index.html — has the markup moved?")
	}

	for _, m := range found {
		for _, class := range strings.Fields(m[1]) {
			hiddenRule := regexp.MustCompile(`\.` + regexp.QuoteMeta(class) + `\[hidden\]\s*{[^}]*display:\s*none`)
			baseNone := regexp.MustCompile(`\.` + regexp.QuoteMeta(class) + `\s*{[^}]*display:\s*none`)
			if hiddenRule.MatchString(sheet) || baseNone.MatchString(sheet) {
				continue
			}
			t.Errorf(".%s starts hidden in index.html but app.css has no rule that keeps it hidden: "+
				"add `.%s[hidden] { display: none; }` beside its other rules", class, class)
		}
	}
}
