package web

import (
	"fmt"
	"strings"
)

// This file is the arrangement registry — the dashboard half of the one in
// internal/ui/tui/layout.go.
//
// Six arrangements of the same dashboard were mocked up so one could be
// chosen; rather than argue from screenshots, all six shipped behind a
// selector so they could be driven against a real host. **C · Console won and
// is the default**, and the other five stay: what the comparison showed is
// that the right arrangement depends on the window, and a picker is a cheaper
// answer to that than one layout with five sets of breakpoints. The terminal
// registry carries the same six for the same reason, and the two must agree —
// see TestLayoutRegistriesMatchTheDashboard.
//
// The arrangements share one DOM. Only two of them restructure anything in
// JavaScript (lanes groups the list, inline moves the detail node into it);
// the rest are the same nodes under a different `data-layout`, which is what
// keeps six of these from being six dashboards to keep working.

// Layout is one arrangement. ID is what goes on <html data-layout>, Name is
// what the picker shows, and Note is the one-line description of the bet it
// makes — the picker is being used to decide, so it has to say what each
// option is for.
type Layout struct {
	ID   string
	Name string
	Note string
}

// layouts is the registry, in the order the picker lists them: the default
// first, then the alternatives in the order they were proposed.
//
// The letters are kept in the names because that is what the mockups and the
// discussion around them called these, and renaming them now would break
// every reference to "G" or "H" outside this file for no gain.
var layouts = []Layout{
	{
		ID: "console", Name: "C · Console",
		Note: "A domain rail down the left carrying every score and every coverage gap.",
	},
	{
		ID: "split", Name: "A · Split",
		Note: "Axes strip across the top, findings list, detail pane.",
	},
	{
		ID: "triage", Name: "B · Triage",
		Note: "A spoken verdict on top, axes as sparks, full-width list, detail as an overlay.",
	},
	{
		ID: "railverdict", Name: "G · Rail + verdict",
		Note: "The rail and the verdict together, with the detail pane given back to the list.",
	},
	{
		ID: "lanes", Name: "H · Lanes",
		Note: "The split pane kept, the list grouped into severity lanes that each fix themselves.",
	},
	{
		ID: "inline", Name: "I · Inline",
		Note: "No detail pane. One full-width list, and the selected finding opens in place.",
	},
}

// DefaultLayout is what a browser with no saved choice gets: C · Console, the
// arrangement chosen from the six. The rail is why — it is the only place a
// domain that could not be scanned is both visible and explained, and every
// other arrangement leaves that to a banner the eye learns to skip.
func DefaultLayout() Layout { return layouts[0] }

// Layouts returns the registry in picker order.
func Layouts() []Layout {
	out := make([]Layout, len(layouts))
	copy(out, layouts)
	return out
}

// LookupLayout resolves an ID to its layout.
func LookupLayout(id string) (Layout, bool) {
	for _, l := range layouts {
		if l.ID == id {
			return l, true
		}
	}
	return Layout{}, false
}

// layoutJS renders the registry and the applier that runs before first paint.
//
// It is a served file rather than an inline script for the same reason
// /theme.js is: the dashboard's Content-Security-Policy is default-src
// 'self'. Blocking and in <head> for the same reason too — restoring the
// choice after first paint would flash the shipped layout and then jump,
// which on an arrangement as different as the rail one is not a flicker, it
// is the page visibly rebuilding itself.
func layoutJS() string {
	var b strings.Builder
	b.WriteString("/* Generated by internal/ui/web — do not edit by hand. */\n")
	b.WriteString("window.HOSTVEIL_LAYOUTS = [\n")
	for _, l := range layouts {
		fmt.Fprintf(&b, "  {id: %q, name: %q, note: %q},\n", l.ID, l.Name, l.Note)
	}
	b.WriteString("];\n")
	fmt.Fprintf(&b, "window.HOSTVEIL_LAYOUT_DEFAULT = %q;\n", DefaultLayout().ID)
	b.WriteString(`try {
  var saved = localStorage.getItem("hostveil.layout");
  if (saved && window.HOSTVEIL_LAYOUTS.some(function (l) { return l.id === saved; })) {
    document.documentElement.setAttribute("data-layout", saved);
  }
} catch (e) { /* private mode: the shipped layout still applies */ }
if (!document.documentElement.getAttribute("data-layout")) {
  document.documentElement.setAttribute("data-layout", window.HOSTVEIL_LAYOUT_DEFAULT);
}
`)
	return b.String()
}
