package web

import (
	"fmt"
	"strings"

	"github.com/seolcu/hostveil/internal/model"
)

// modelJS renders the enum vocabulary the page needs to turn the bare
// integers in /api/result into something a human reads: which domain a
// finding came from, how severe it is, what kind of fix it has, how its
// domain's checker fared, and which health band a score falls in.
//
// It is generated for the same reason /themes.css and /theme.js are, and
// for a reason the dashboard supplied itself. The domain table used to be
// a JavaScript object literal written out by hand, with nothing tying it
// to model.Source; when the sysctl domain was added the copy was not, and
// the dashboard silently stopped offering a filter chip for a whole domain
// while rendering its failures as a bare "10".
//
// Generating the domain table fixed that table. It did not fix the habit.
// This file used to end with a paragraph explaining that severity,
// remediation, and scan state were "closed sets that have not changed and
// have no documented way to grow", so mirroring them in app.js was fine and
// generating them would be ceremony. One screen away, app.js held a *second*
// hand-written label table — keyed by axis ID this time — which had fallen
// two domains behind and was quietly substituting the long scoring labels
// into a column sized for short ones.
//
// So the argument is retired. Whether a table drifts does not turn on
// whether its enum can grow; it turns on whether anyone can add a row in
// one file and not the other, and here they always can. Everything the
// browser mirrors is emitted from Go.
//
// The one enum deliberately absent is model.FixVerification, which solved
// the same problem the other way: it marshals itself as a name, so the
// browser never sees an ordinal to look up. That is the better fix, and it
// is open to any enum that is not already on disk as an integer. These four
// are — they sit in every persisted scan snapshot — so their numbering is a
// compatibility surface and the table has to stay a table.
func modelJS() string {
	var b strings.Builder
	b.WriteString("/* Generated by internal/ui/web from internal/model — do not edit by hand. */\n")
	b.WriteString("window.HOSTVEIL_MODEL = {\n")

	b.WriteString("  domains: {\n")
	for _, s := range model.AllSources() {
		fmt.Fprintf(&b, "    %d: {id: %q, label: %q},\n", int(s), s.String(), s.Label())
	}
	b.WriteString("  },\n")

	// name is both the export name and the row/chip CSS class; abbr is the
	// short form the fixed-width severity column shows.
	b.WriteString("  severities: {\n")
	for _, s := range model.AllSeverities() {
		fmt.Fprintf(&b, "    %d: {name: %q, abbr: %q},\n", int(s), s.String(), s.Abbr())
	}
	b.WriteString("  },\n")

	b.WriteString("  remediations: {\n")
	for _, r := range model.AllRemediationKinds() {
		fmt.Fprintf(&b, "    %d: {name: %q, label: %q, fixable: %t, auto: %t},\n",
			int(r), r.String(), r.Label(), r.IsFixable(), r == model.RemediationAuto)
	}
	b.WriteString("  },\n")

	// complete, not ran: the dashboard asks this to decide whether it may
	// call a host clean, and a degraded domain ran without covering its
	// ground. See model.ScanState.Complete.
	b.WriteString("  scanStates: {\n")
	for _, s := range model.AllScanStates() {
		fmt.Fprintf(&b, "    %d: {name: %q, ran: %t, complete: %t},\n",
			int(s), s.String(), s.Ran(), s.Complete())
	}
	b.WriteString("  },\n")

	// Ordered best-first, matching model.Bands, so the page takes the first
	// band whose floor the score clears — the same walk BandFor does.
	b.WriteString("  bands: [\n")
	for _, band := range model.Bands() {
		fmt.Fprintf(&b, "    {name: %q, min: %d, cls: %q, verdict: %q},\n",
			band.String(), band.Min(), bandClass(band), band.Verdict())
	}
	b.WriteString("  ],\n")

	b.WriteString("};\n")
	return b.String()
}

// bandClass maps a health band to the meter's fill class. The boundaries
// come from model; only the class names are the dashboard's own, which is
// why this mapping lives here and not there.
func bandClass(b model.Band) string {
	switch b {
	case model.BandGood:
		return "b-safe"
	case model.BandFair:
		return "b-med"
	case model.BandPoor:
		return "b-high"
	case model.BandCritical:
		return "b-crit"
	}
	return "b-na"
}
