package export

import (
	"fmt"
	"html"
	"strings"

	"github.com/seolcu/hostveil/internal/domain"
)

const htmlTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Hostveil Security Report</title>
<style>
  :root { --bg: #0f0f14; --card: #1a1b26; --text: #a9b1d6; --muted: #565f89; --border: #2f3348; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: system-ui, sans-serif; background: var(--bg); color: var(--text); padding: 40px; line-height: 1.6; }
  h1 { color: #c0caf5; margin-bottom: 8px; }
  .score { font-size: 48px; font-weight: 800; text-align: center; padding: 30px; }
  .card { background: var(--card); border: 1px solid var(--border); border-radius: 12px; padding: 24px; margin-bottom: 20px; }
  .finding { background: var(--card); border: 1px solid var(--border); border-radius: 8px; padding: 20px; margin-bottom: 16px; }
  .sev-critical { border-left: 4px solid #f7768e; }
  .sev-high { border-left: 4px solid #ff9e64; }
  .sev-medium { border-left: 4px solid #e0af68; }
  .sev-low { border-left: 4px solid #9ece6a; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 12px; font-weight: 700; text-transform: uppercase; }
  .badge-critical { background: rgba(247,118,142,0.2); color: #f7768e; }
  .badge-high { background: rgba(255,158,100,0.2); color: #ff9e64; }
  .badge-medium { background: rgba(224,175,104,0.2); color: #e0af68; }
  .badge-low { background: rgba(158,206,106,0.2); color: #9ece6a; }
  .meta { font-size: 13px; color: var(--muted); margin: 8px 0; }
  p { margin: 8px 0; }
  hr { border: none; border-top: 1px solid var(--border); margin: 20px 0; }
</style>
</head>
<body>
  <h1>Hostveil Security Report</h1>
  <p style="color: var(--muted); margin-bottom: 30px;">Generated by hostveil v1.0.0</p>
  %s
</body>
</html>`

func HTML(r *domain.ScanResult) (string, error) {
	var b strings.Builder

	b.WriteString(fmt.Sprintf(`<div class="card score">Score: %d <span style="font-size:16px;color:var(--muted)">(%s)</span></div>`,
		r.ScoreReport.Overall, r.ScoreReport.Grade()))

	b.WriteString("<h2>Axis Scores</h2><div class=\"card\">")
	for _, axis := range domain.AllAxes() {
		score := r.ScoreReport.AxisScores[axis]
		b.WriteString(fmt.Sprintf("<div><strong>%s</strong>: %d</div>", html.EscapeString(axis.Label()), score))
	}
	b.WriteString("</div>")

	b.WriteString(fmt.Sprintf("<h2>Findings (%d)</h2>", r.TotalFindings()))

	for _, f := range r.Findings {
		sevClass := f.Severity.String()
		b.WriteString(fmt.Sprintf(`<div class="finding sev-%s">`, sevClass))
		b.WriteString(fmt.Sprintf(`<span class="badge badge-%s">%s</span> `, sevClass, strings.ToUpper(sevClass)))
		b.WriteString(fmt.Sprintf(`<strong>%s</strong>`, html.EscapeString(f.Title)))
		b.WriteString(fmt.Sprintf(`<div class="meta">%s · %s · %s</div>`, html.EscapeString(f.ID), html.EscapeString(f.Axis.Label()), html.EscapeString(f.Service)))
		b.WriteString(fmt.Sprintf("<p>%s</p>", html.EscapeString(f.Description)))
		b.WriteString(fmt.Sprintf("<p><strong>Why it's risky:</strong> %s</p>", html.EscapeString(f.WhyRisky)))
		b.WriteString(fmt.Sprintf("<p><strong>How to fix:</strong> %s</p>", html.EscapeString(f.HowToFix)))
		if len(f.Evidence) > 0 {
			b.WriteString("<p><strong>Evidence:</strong></p><ul>")
			for k, v := range f.Evidence {
				b.WriteString(fmt.Sprintf("<li>%s: <code>%s</code></li>", html.EscapeString(k), html.EscapeString(v)))
			}
			b.WriteString("</ul>")
		}
		b.WriteString("</div>")
	}

	return fmt.Sprintf(htmlTemplate, b.String()), nil
}
